name: OPPO A1K

on: [ចំណេះដឹងផលិតផល OPPO A1k
ចំនុចលេចធ្លោទាំ 4 របស់ OPPO A1k
1. 6.1 inches អេក្រង់តំណក់ទឹក
កម្រិតបង្ហាញ HD+
វិមាត្រអេក្រង់ 19:9

2. 32GB ផ្ទុកបានកាន់តែច្រើន

មិនចាំបាច់បន្ថែមមេម៉ូរីខាងក្រៅ
តម្លើងកម្មវិធី ថតរូបភាព និងផ្ទុកឯកសារបានកាន់តែច្រើន

3. 4000mAh ប្រើបានកាន់តែយូរ

ប្រើធម្មតាបាន 17 ម៉ោង
ប្រើបានពេញមួយថ្ងៃដោយគ្មានបញ្ហា

4. ColorOS 6 កាន់តែងាយស្រួលប្រើ
ប្រព័ន្ធប្រតិបត្តិការផ្ដាច់មុខចុងក្រោយរបស់ OPPO
ដំណើរការលើ Android 9.0
មុខងារពិសេសៗកាន់តែច្រើន
Game Space 2.0 ធ្វើអោយការលេងហ្គេមកាន់តែមានស្ថេរភាព
Smart Bar, Game Assistant មិនខកខានសារសំខាន់ក្នុងពេលលេងហ្គេម ឬមើលវីដេអូ


]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
